apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:V1AWhoQzkPUM2pgZRPpu2tU9gsnFCNh/fgHBbx9Deyv/oQg=,iv:g2b8RkFVw/7BmQ49PSwYYusKIxzVbfLYhgbEE3OWc9Y=,tag:1JZWAkqfG2P9WBPKsmXRww==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:he7ha0jcozzfSXkkWNYDq1r9Z4+aBm4QmLDZ6lTk30jrkEsDFQ==,iv:Lxdy95LmEmqhgedMJPXv8lNgTUXXirModvn+ffx1Unk=,tag:k1zyJRcW7vSWwMuhHyNeag==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Xjg7whRtEXBhwvSeHb8UK2a/hsbNxav4fA==,iv:aqpdadvTmgnLeZ+7snKhVfZYLV46afjQ+/Qc3Z8f0K8=,tag:TQTJR40Qi7x7C2f6EbsWLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcGw0RlJLS2ZpVmF3WWxV
            UERBL01taEs2T0piRWpDV2lIenA3dHJDRUhzCnZOMFRna0V3ai9MRVBmNWs4K3VH
            TFAwVkJFVU5zRkgzVTcvTVc3Nk1EVmsKLS0tIFNuR0tiWVJPMkpjbHFUOW5Ud3lm
            UmV3bXVITTFWcmhrVHFtck9IOEpyMmMKHESXqgwAiCeOcvqxRTWr/HMsGHZI0dnt
            XxmB6hh1BFUD0a/QYZhLi2PhcjWZUIzJokTUTJWi1h1fiKdRdJyv+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T08:09:46Z"
    mac: ENC[AES256_GCM,data:kLFNmBHpsh/oFOrPICL4p/G3380IUIVvZJPJp7v1uBpdUpAL59VeZTBzDOhLd8oZ/DL7PnLDWw7zWPyspxW5HMI/DXPs+t2pbJUkBFUUxkXPrzGUcdJXCpPSnUwxik1K3Mu5KyWKr4nSEaa9OYXmraa1ozvhNM+MGlx77/yLwQ8=,iv:NGPMQQq5XV21a0BQaOhRc186jmAe4KDeGpHyeUjGSbc=,tag:HjoJOdA60ibHW3V74m4FrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
