# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-traefik-bouncer-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:kLNR22gwocpYI7yp7B4KgHpQVAENQBJDflAe3oDmyZ8SSQIkRZQtnP2UuxrdvAgWBu63yk7j/Q0Yy5057icmAI4jZ4e4COlkG6QJ3byr61IvuFXhIMBMIn01oSPHpghzMR8Csyy35kb5IqR9AXxX2OeBR1guJetuyE2Nc3dxM9Hgghv4K9Ivkp019eztRfpUKu54DJ5rxxYVyMqXZzIkR8fPL0sPtpM9iW9YUQEXhGy/I4XBvn9w8hpY6xGc4SZ5fhvXJi29da1I1bzpBFqeXyPIpJgl+tY=,iv:4xkMdZbTJVGkveByYKtWvNJr61o7Jrdq+FJAmlkIj6U=,tag:qszBSpnERoZmHdRU6co7cw==,type:comment]
    #ENC[AES256_GCM,data:QDiuWGVT612Tq7hSYURBIJPMSrD7N1doOU84GUZIm2L2gnBx0eL72j+7q2t/QWETRkuChSsrKfCJBFRz4lO+XNm7Gkwkr+qt6AdTLPE4oUOQmX4zfHN1aEnQAcKmillWTEAiH4lXvP/Y7nctr6b0yTqbxVUYw85DIKXZBQ0MMwZWaT2NpscEH9Irt/o+pK4pQXoA7JCJKQf5ibKNLOwv3QinvN6J8ZSsEhu4/KtZfD/GNHk+lDXQ7esSIvop47xL3pOjrRHG7zy09Gv/aJ2+TzXsbW9zCMaSE8f8gXr9Qm+AEMo=,iv:ofTMnM42pu+ROfFYco18r5ElUGqbu3WVcwF2nkmE8aM=,tag:D7HAB3agXhI05Mu6g+Jo+g==,type:comment]
    crowdsec_bouncer_api_key: ENC[AES256_GCM,data:6/BPxfs/F0vodhxKw/CBv85QkdeDN+TUvCC5vuh/BEk=,iv:DC+2u7lWqO0xeLTc7cuQfN9LUKygHBsA56nhsvG1hKc=,tag:xLlmcurc1vh3SIUKYeP5+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSWhZejJ0OU1yOXRKckM2
            OXJqS3F1azRaSDFTc2wyUWxvKzlGbms4U0FzCjVVNWkya0dWRWhiUVE1bTFPeExi
            T3RqcG00Ylp3YlRKSEcwMmxZVnNGUHcKLS0tIFZVTXYzc1BWVnVqTkNtUFQxUWxV
            ZHVMRExZcFBHWnpjamdDRndGSFVSMzAK6jS5H8DFezx34kZiD5eOGbH1Inj+3QiL
            tJmfkvjgxLyH1yPo2kuw/rSt/zrw4xWtUsmtTSZoyVqb1zDBtoTc2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T14:39:47Z"
    mac: ENC[AES256_GCM,data:d1L271PBgmXLsDGGiLZvFbo0/AfWLb9NlCnVPVzjlg7bVbMuGoc1Dll672zmN6d2Q5UU7D7zXBHnrmrjPnIyvRHSHGMb9GjhrccZ8P7iQyIoWGU4OqBKUwmNmTcmgVfx8KfRxmqD94MF8uGU2LNou2ZDx/kjxj0/5pEhrUD4VxE=,iv:fLYf/BZ0x30JLHBaXfKGBOrVwFfmRFreQRqM1E9HWQ4=,tag:Y9jWXAx7bJk+9xvZ/zvuwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
