# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-traefik-bouncer-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:2J/CTH7nZ0kS0ndxqrD/tslfmOu7sysKTFJ56xN5+IuFyDTQAVFOsHeFXlR5SL96ytS5H/cFA39uGXP0J5Fux8ich/l5r4/Rbn9XvRGD,iv:oyUI4QdsdRobNeaO0oE/bp3PfxhbGo11Kx+IsHZFroE=,tag:Ssq0w/+SJ3JnnbRRSG63/A==,type:comment]
    #ENC[AES256_GCM,data:OZjqnI/c8RMLCtyVUtBS0+8A+rvdSZ0Zpydz86UsFFy8nuIQm/RGNiwx28dSWTwFUkZIq06DdqKPInCHmWAdxniXZtD6GQXd1Im0gh749w4b3fOivg==,iv:cgcgfHukFECmFGcFQ72+zB/i/zg9DTEFQFR7J11jQVM=,tag:ZfWudpZPNHkZvI/npRbw1A==,type:comment]
    crowdsec_bouncer_api_key: clfp7qhrm0000mn08lqhymal0
