---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-nfs-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Mi
