---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-ext
  namespace: networking
spec:
  ports:
    - name: http
      port: 80
  type: ExternalName
  externalName: "postgresql.${SECRET_DOMAIN_INTERNAL}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  namespace: networking
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: "traefik"
  rules:
    - host: &host "pgadmin.${SECRET_DOMAIN_INTERNAL}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-ext
                port:
                  number: 80
  tls:
    - hosts:
        - *host
