---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - cron-job-tag-tracker-errors.yaml
  # - net-attach.yaml
  # - volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/instance: qbittorrent
