---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: 6.14.1

    service:
      main:
        ports:
          http:
            port: 8080
      webserver:
        enabled: true
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: ClusterIP

    env:
      TZ: ${TIMEZONE}
      PUID: "568"
      PGID: "65539"


    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-0
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "business"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: calibre.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - calibre.${SECRET_DOMAIN}

    resources:
      requests:
        cpu: 0.003
        memory: 1Gi
      limits:
        memory: 10Gi
