---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - helm-release.yaml
 - service-monitor.yaml
 - prometheus-rules.yaml
labels:
 - pairs:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
