apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Jr4qTxLxqkl8OzwRGqc+msdViJR+QE+HyvVCYzr0RlJotWNAyg==,iv:Y0Ko2Po7cfmvqtVPAA3bf6etLm5PRJt1HGS5ZxzrBx4=,tag:McC8boQiejORNUxEHDkQKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOCtXN2daMk91NCtJNVN1
            YStVMmhrNWpkbnh1dWQxYy80YVZ2dHc2bFVVCnBSNWlTN21hR0wzKzlKckNPTklQ
            ZUVWNEFnQjVWQUE0LzJtSFBFRDByZlUKLS0tIEt0WEwvakRhN3krZDBSYU1lTS9r
            Nys0a3FhNlEyYzY0OE1vOU51YzNPM3MKaiX6moQzpft1kd2/xRMdo4Wg0yE3P62b
            hJlnQKq8pHaBCy9kf4ihm7OkEAd1jA4MD99tBB7Pnlts63Qu0XU1Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T08:35:59Z"
    mac: ENC[AES256_GCM,data:DPUMQn3jAJOK9mh8pwHgyOqyqT/trD/F/p5gxbswBRYESsqTBqcXJh6BUuijWube+eVVgbF0tlvbOGOZ2V3PtyXBrHeV9L0kA16iTMiBrSAZtPzVQLTuQO5LThvcmh+56dLrkQv92f9j9QGgN+yDJcmFtHRKyN3zd2SOlDP+rwY=,iv:dVqiGEHxrOo+u0yckvjCcP4XoBWWyK66bXhF7Cn/vLI=,tag:V7iExziDFFotygt9WbnPZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
