apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:mqIEvdvq/azEWTX7yaoxhNvd0vzVqoHJr1yJDirXF0T1fMc=,iv:yxhNwuSPNPrvIEkazb5NJA6PKlM8ieHw8994ew2p2Bw=,tag:Dd+G5pxZaF3wEHS3kvVonA==,type:str]
    api-key: ENC[AES256_GCM,data:GNLNM2gW6zUsbGBl3lZ6/3uiiIQ16CTGKJlA70tXIcAtZfi0sg==,iv:aGIqZ/rTZaHJduP5AYtrCncSlhoborAJz2EcxqjoOLE=,tag:3sEdt4KFBkX4JZjm3QZT4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQzg1aWlJazMzMkVNWVRR
            RlYvbW1XOGRsRXRPZTJIeURMOTZKbElub1dFCitPU3pVSkVCMzlrb3hGamVWeXdJ
            N1U4cDFBMUU2djFTQUN4L1VtSU9QYTAKLS0tIG9nNXFXRE0zTGdqT2ZDWWdIS2gw
            Wk1WU2M3Ukl3bTR1UU8raDhZY0t5OVUKKARercQTkNmkf1lRogbeghvYYoTUFvy/
            /FjFZAq7mFfEemds+t5U9bDF8Uuc5n62UxTtHP+tGldfL6sQru2EzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T08:35:59Z"
    mac: ENC[AES256_GCM,data:lw5+u9HD9aBYbWZSLyOKEg+yRKRGDHVAdiol+ktLya7iYUPS97q1fJiy3kBn6sfb0OU2v1HQSb3espb/h4kUH+VQ38bRNZjscIULvidhrLIKbLXOjm3AnBLbsnzH2Ca0KaQi1G41PBwYSPhVRhWnGaqY5RuT13JqXB+A3YE0Zxk=,iv:rGIRwP0XfJw4no/pUIf9sKmA+VLlmv82irJJ2Zc/FOo=,tag:b35Z34uuYvW0aP2OY0zArg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
