---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # renovate: docker-image
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: "1.3.2.2984"
      pullPolicy: IfNotPresent

    hostname: prowlarr

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      # fsGroup: 568
      # runAsUser: 568
      supplementalGroups:
        - 65539

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
      backup:
        enabled: true
        existingClaim: prowlarr-nfs-backup
        mountPath: /config/Backups

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "downloads"
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    resources:
      requests:
        cpu: 11m
        memory: 127M
      limits:
        memory: 508M
