---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-cephfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
