---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-canfail
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
