apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:jomyxg27v//Gr2sHioNd8UCtgLpCg455wADbv0SbBhyrnRCfviwJU9VVhN37xWJLIMUwMVGjm6FyRVzi,iv:rgYBI1m2y52LA5WQw0xJdSZltc9MN8gB2eZwioB65zs=,tag:uDZG/ch1LtTAhCPihEUaBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc1c5bEY0NjlOdERtS1N2
            TlVDbVQrZ2VzVGZOY1hKUkFYaG5uVEN4WldvCk0zUjBZM2EzbzdPb05yRTRyZ1Zy
            RG8yRS9FdDFHVXVXaGE2Qnk5Y0JnOE0KLS0tIGJ0UVBON1VNNHVPb1JnaEx0c3JF
            MVMwU1FMNm9FR09uR0hrUU9Pb0xsVGsKOoCbXC6IYzRnmoH0oUJiqM4HmZL4+MNK
            0qAQGIWEECfGER/df7FhzmHL49E6M0LfqF0EEqN1SlvDJ5L4Ibe0lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T08:09:46Z"
    mac: ENC[AES256_GCM,data:1v8YIqHDnmKrdCWcyXo+D9e+o1Xg2EIUTooAgKhozvzmx6X08luZvIOpX4HPSETPwYnY9hA78aH1MIC3w8ciIVpZD2bsEpZj6YSGKe4z6SmULsmdS5HSQqP7gAjfklSWtiREMWbmxHcpd4xkl12864TTqj7W/is6F3BpH/Akp8w=,iv:H7Cb7hv8d27yAufcGNXHueA0qgE8FPmZJ0NXqPxT6Ec=,tag:kzRNk8i/rESe5Xnd/xKkAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
