apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:wUGdc+R7fWKQBDKenykFXUIZjx12DerBUZiqY38kI9euzD27yMAKVFKTpYxBZ4yEwTlFdeefTaGKG+7d,iv:AMXNiAjRQzCR1rdtcn8LaTETMd5/TYxrRFBQTakct68=,tag:7lf9Pi+iW5M58oLddyMVSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN1lNNFlQQ05IT0x1RThQ
            Rkc0SmJJak9PdzdEejhHNDk2VHp1SGpleFUwClZJZFJkWlNzWFlZWDMyUFdrTjBo
            d1ZERzNrZVhMaElPaGxJQVk1NS9WdEEKLS0tIGFUSVBuN3poc1R3SEZic1diQjVL
            SUUybjVoUVREYXdsdlk1b3hPNnVrYzQKlqOMqpTDEf7fiB3XmU0AXeBB1VXPSSAy
            U3UXUw52Zj5ToltBxKSZsDE/0ESZ4aeayBYOEgZMrTbzYFaDPShUCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T08:36:01Z"
    mac: ENC[AES256_GCM,data:h2a0ECBIvK8a82TWXZI34C2pcWQeFkPpv41a49+qxB77AdjdqvHHzgXIdXxIFSnv+yROPNnKZzup7VvTNLIb05sWkn3dF9s1Dtj6QK5d3SoJ1SrhBovMrOg3C1c9DQ4BRvZ2pkZ5LO+ScUa3G9lhYlVDE810NpKAL5C0OZ7DH7s=,iv:ZRV6XlbmYrJD4UuZLhnYma81YB4U+QyY1sffVscOZ9U=,tag:/ZJ8rNFY15eF7BAx9yOpuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
