apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:eS12eubzaANmPWKXR/4Xa132PMZscm8itTJ3BDdcvxav9gsmOn1ol/IR4+fliLbw6oinTqqVi5nyZsEd,iv:58cQFMkPB5D3RviM7Cvqy+2G8tc6zkshOqWTiA5isY8=,tag:saZCvko73uollNxZXRkYvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNkl5M3c4QUs3bTZiNS8v
            NW43MUxieElaOXFoOFJlZmhWUUhCcm9yUzJVCjA3Z1dYR2lKQ3hsUGNTcnExS0hD
            N1NpQ1EySHdDbUxKNnhMN0VFT0JxSDAKLS0tIFZzQXZyRWxQTFZya0ovT0JqZVdV
            UUZ6Z1NiMUVGU0ZtQ1NJOFNWK1JubDAKpiDz4UPNOEt3KFIpCTvZSP2vM/X5Fj84
            sY657EjFrEWCBEQY4qmkBLz+DnKx3xVfdVIIxovrvyuqoDiw74Iylg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T14:41:57Z"
    mac: ENC[AES256_GCM,data:V3h2PEXWOyy/thGGwTTwTWVLkQlYT5PcKHIKNbSwHQHPjAmk+iBTfAfASWweZWogdMocHKM15OqzaXVuyRuVLlTtosgRpREmR6NWbMcbOZ55nnfxg9VkO6r7+z9FBWPkiT2C0F0m15uq8+2MuNG+u1BdkyxNRyfqyszA7HzEIB0=,iv:juKskrQyJrHKuCgI970furgfksyFOjqSNVmUWz5IAQc=,tag:hHzm1Sc5T9qwmL6Fbe3MKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
