# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-basicauth-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hEOHFWkc,iv:qA5ISKBEEVDskNGyGHY55qrc8YFWvcSU1KqxPSVCUt8=,tag:8SZ4GpKWBzNV9jTMctrbpw==,type:str]
    password: ENC[AES256_GCM,data:asdgagk6QV7Nx3qI4YTqhbFnrjAIkTzr,iv:vAID6ejMc6+wrWuKuRYmZvvepbzDcR0WBAPFMyy+IsY=,tag:MSt6HG+9eblmEwbOO+Zm2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR1RORE83NmxqRFdMNHEw
            dG9jdkNjbWNzby9NYklkam1qNGtqRU91KzFzCjhpb0xyNjB4NG1MRlZuTUFqdlZK
            QUIyNXlmbEJvSlZBWGdXaTcwNVNSU0kKLS0tIFFlQkJGc0tua0w0TXg1TFRUWmxn
            dFJCQ214ZmJkSTFKNmlPUHlEOU1ITDgKuGon8VUq58fpgIAE1VMgd7pywxR2babb
            f3QPwV+6CIfCOI95wo4lKApYBU9ukxHLu3/H2ksMqDwoPM7nRTZkcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T09:01:04Z"
    mac: ENC[AES256_GCM,data:VCZ7o1WgJG23AgyC+8Kh2xZWZgqnxKLqwCCyWPIaThFTyXgfv+8JM8TzNhGh2vPWr/E85kUMYuk+Zx3wzUVwAfK6BzhnxzhQgsppByBWAD3K6Sm4qVN8im/1t4LMKby4PjqvxtRbdmw5ib0MgcJ9r96XfGc+VZp/3k7Sqw0YWUg=,iv:+pGDA/KXNO9TvoZki49aiaH3YEhRJr+sD7PVCZl/hDM=,tag:pB3CqFzvB1F+TSMtHFlLOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
