# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:2ly9s/+hzk/JisA/u7slH8gVnpOqBVITWS2erDlO1DRrbiwBvFkk9fJAbq7Rz0fro/FpSpkO0fwCgwv4z4nM1IXhxy1EZZooUvUC99VGdQh0yHLgcY9XHh8y/zJoYxHkSiWns4a85zspn1Wrubti9mg94WKHJh1bB1OXdeu+R1IjN9EDmT+ZXE3LvT759abFyX/PZVg6jkrjFRQbCOM6,iv:PHIP4TsN0sT59eUGgcj3PB90PiVXMI0oyS96jps6FJ4=,tag:6SCb2DiaInxpS4O9M09rcA==,type:comment]
    ENROLL_KEY: ENC[AES256_GCM,data:zH9GYhIZ//y5LD2sWpbKiVOTrgygqynNAg==,iv:fRuyFkb3jlOJCKkZulVvO501MHlyTlu6xOS5H/mfVTo=,tag:8gUEeAnV6Gjxl2gbrdo3Mg==,type:str]
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:8/MacoI/BpH+qglCNesHbNfHzaNyVICr0A==,iv:kdV5r894roRoZcrynoHAffBZ/LsCT3F/jag9Max/0Ps=,tag:mj+vERntSAg9PoB959ew9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdC9SbkZsOVdrNlE0TUYr
            aXllWGxwakRoN0MxbkNpZGpidUZqSWhxQjBFClZvZGIycHRTVzlNR2Q1RGlXUzhq
            U2NaQVhpemhrUGdRRXpRcjhQNWFTbjQKLS0tIFA1cFo5NFJGb20vR3RBVHg1Wm5Q
            YnFlemVRMU4xcnkxVG9mZFRYb1A1YlUKi8Uua0ZsMep+/jv1mXBmVi+hcWUFwxOY
            k9fYa2GhB4pKXX5cZdO+vVsqp/Gk8JuB29ikASM41CvKvP0iLQrO8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T09:49:46Z"
    mac: ENC[AES256_GCM,data:m91YzwJtZRYNI7CGITZSyVO/VQD5jm1ZPSS2i8xHznC3zqW690uSBQgZq8sgrFJtY8hEAxFbQVKD2EchMxW+my2xQQwclZ/lSAlm92uS23nLq0RBYHXnIA+AIL6B2Qrmi1VgchIX1S3g1oUraMg42IxWttkwKvzrperAcX0ADFM=,iv:vYl94JYCvcz9eciekAh6eyJhvjt+Ktd/dz/vuAzoOMA=,tag:N19zEiem1w/Oit874w9VYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
