apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FQX9t4+Ao3k8XA5IUXydKbkDbYE=,iv:JxS7T49mmW8Bxv8tN9gwc49w8eZF4WBu11Le/amGFEA=,tag:2BPMpVf5GhInrml3jbbBYA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:D/BDbfo1N9AhKtXLQony97Jm3qYJQjhOOjrMKWzWrQw0nME=,iv:dcA1VifjJ9w0TyHuyBlpgBdRKSc1H0vE/nfa7XbP3lc=,tag:G57soplE4L27P/LZrQY9UA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:5FLjfrY2LGRZDfJPnnmOU+rupuD8dgokFV8=,iv:uSQi70mmNIoI3ktKd49Z/Rc9NRjAsIsPiFbGpwcjdvw=,tag:qRwN6L11qqsR4V6L/tXfXg==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:OPsEKYXGy05TwTCX7C+5XyO0MkmUMixtM4uC9aJZKtXXPKmr34JLvZAYOU/N,iv:0ZqA5TyCmA+jxCQ8PHJNrnoa0YtKxagGcya1JwU778A=,tag:u0dNySC003jSFPpB6Qgi5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QWJCUXgyOTJINGllVm5l
            N2V5MUFNbXppazNKcmZyY1UwZGp1QTFkT0d3Cm9rQjdyRVcrN1djV0hVTkJTVC8y
            WVB6YXMvcGM0RDIvNklRVWRiV2pWUncKLS0tIHg0WEZ1ZlYwUkMyMVNUQ24vdVFB
            QTYxNEI1dUs1UFFKODNKNENybUQvaG8KR82GrAgulC8FAWTAlwkdOXjFZqGJ/fly
            7323rUKxiPyXlUDx935A9I/Efg3qyfHgQP8TK66JLKAA0o6cMSI3mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T07:37:58Z"
    mac: ENC[AES256_GCM,data:mvfn4EdiDmBL/sV1utUICbkx4a5oRM7fwT+S7xaKl9PkCLGviUDQHZwYmF5KiQh5Q4biRpZ0lAPIVTiP5qd7TBU05RxZSi7OhQhwBVtvx9IazecPf4/Wxv99ALKHopohz4Rt9ToVgK2GxrrKfb6CTmtcWyYy4PqoTUvK7UGPhp0=,iv:+/oh/RJjZyl5Ow4Gk/yhjddW+hCHoV9mp+A0mHWH4b8=,tag:hy61mGGpfxZEaa6U6+aBJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
