apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:x1HdiolUbqPQ3JzKdmHwuhpn3Us=,iv:0aFISULsQgTsr6Nl/9XTO0Ql3PiWtsAZAajWJOujRb0=,tag:H6ahP0EII3YXXIkw1tZzvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:P3VVjKXbr0/4Ir9OAZEUXoRsR4wK2MctAUMfLeuceYoVLkg=,iv:Wby6BZHWS+3zbGn1DTDJzloUEHbaGxoexIlgI/i7MQ4=,tag:QQgHAFP+GT65BNboQwh5DA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:uBrB6AwmOQ/ei9XE3v8UQcuRNs8fH1ZNOWo=,iv:1EoY+Nn+0FEhvc4LEK7Qt1TJJnWU1KmmFsAty6Pqbuc=,tag:c9J2vJS/BCiekhY9vDHBWw==,type:str]
    SECRET_PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lAqKpBEUGQohSbE=,iv:D4zjNDOUa4+/lQUrZh34S9L6h7kRFVK+GFyINub9kS8=,tag:/mtKgtCdh/DzaHym1A6tnw==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:oEP3PYp9f6sqmD1VoSLzY6mT5Ned5zKDY/v1eUlPSa8yAiQVdGsTD9gv8iUX,iv:hUMK2sCYtCmfiSZXTKlRFg8vyl/ARzVQN3xSoxGXpQE=,tag:SwXyaS3uktM/PpeQi/oFsg==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:8KMTgj7mgsUgzrKiXStDe5RTpA/ecRUpkDU2Jw9w8950z5DtOso=,iv:nBcYR2yMyttyc6PGPptgnbAmSiaQY2HBC6q563LbIaM=,tag:17dnAyfAhz+d+dNwfytOGA==,type:str]
    SECRET_GITLAB_PGUSER: ENC[AES256_GCM,data://5d2pmanwdDFf0433E2l0RwNA34qit07fU=,iv:G5xl8/kTcvTHMDKQjHlCxkUO+GfXGuP+tAF/LHmZWhA=,tag:5+fuC2RoW8GjtYbfJgg3HQ==,type:str]
    SECRET_GITLAB_PGPASSWORD: ENC[AES256_GCM,data:Zr0/LVpAGSppGSi25rwXWh57SDPlfQ==,iv:CQ+KU6wlSK5LzVAZOrEPPPqSLSpJ6RjfTmok1JjqKSU=,tag:qF/tXfUDoKwyO0xhp3Fhdg==,type:str]
    SECRET_GITLAB_EMAIL_PASSWORD: ENC[AES256_GCM,data:rUXAXARrytM+WbPQjr97PS21RbU8C5pAz2xzrjRWqVFqBMRzRA==,iv:nhMT7LKA+JG1cc31LxkuPg2Jb7rK/5oZ/ft/K3t3JLs=,tag:mWARBHwPPDMFyLIaVnWs1w==,type:str]
    SECRET_CLUSTER_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:vr75hgWb6Ga5Plm6LB++79JjK2PyJmM=,iv:ZnSN/JL4j6FYmuaBzerlljuns6HWbZ9+IEVuS58kuM0=,tag:EhgpRfyM1J65EBXaxEtj7A==,type:str]
    SECRET_CLUSTER_MINIO_SECRET_KEY: ENC[AES256_GCM,data:rdrtnAjNIB6hpYaPZzyZBu0DLVyXB6M=,iv:RlrfWALUzneLmWwKw0otHFNWO1czdnBkcpLXwfWfuR8=,tag:niPB2RbDGlQYYGNpy81pYQ==,type:str]
    SECRET_READARR_PGUSER: ENC[AES256_GCM,data:m658S9dllfFhKaGV+R5bJ5LhMLrmAw==,iv:C0z4SoaHfbRj/qECYsGTcBB0vYG8dFB423AKes6quc0=,tag:Xmm6bhnjMpi5u4w2mr5HCQ==,type:str]
    SECRET_READARR_PGPASSWORD: ENC[AES256_GCM,data:aKQWEbDIfgCSiowVA01qXAPSSgZ7GFD3Dw==,iv:L1Oz5zA9A7zkv2oE6vtjeH9wgWUKhnpSEAAe2ysFhgw=,tag:JISC0zrAvywvs62ZhvdLSw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1rWIZMp/x0PgRBln7t38lK1PV4F7++zJB30WcU8bG7ySEpjL,iv:Yp8DOFMK+vUwxF72ehpIVHDoz/DPta0DHFZfKKGmvfM=,tag:mTOisvIUZrWr169eKv5GFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZHNJZmdvaWU4WmdpVmNw
            TXE4QjFpOTZVeVpSaHpnVkZGZ2ZrK0hvYnk0Cm9IMjlMeXpvVEcwbFJyTFdWNWpl
            WUxtTWRqY3B2RXRhSjMwcGhoWHZQa3cKLS0tIDdWOFJLL3NpaHZYc21BYXZ2U1JC
            YkNmKzBOYnphNm1KbUh4ZSt1WkR5dEEKF4YueKRjmNJAn0PR2+wPCvn6LdtY1VzD
            cSc8AgMhVwAE9gp4N/rUYETmRLKqkAZoIHc3ZPEHjUY6Zw+0isxwQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T08:21:08Z"
    mac: ENC[AES256_GCM,data:Y23+RhXbsOt54ZZXpJ70q8Ka1VBk1fQgezTJhUx64S40AmMml6zcZixld73JMgDjHXs9TumqXX6m3MtSzczTcq1iL6c97obQkqbDDgEpe8eY4H/ND49vgkrcKRpeSaqlHwnSxwOeJ1Urv2GJAGU4HRtXIy45yeZsH0yy8WgF+y0=,iv:88kP+m2OAZtz8zQ9kRqHCF2jUxRw8Zdr2YIohM9ZNnU=,tag:8zR+hQpMt8qhFWGTlS62iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
