apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ISapfg6ZMmAEq144uaJOjI0OZzQ=,iv:Hi9B6Uqt43tOatQZPO3CGoaAqMJAWOHSy1i0ZU5SsfM=,tag:3dtfXOzPp/zu/CrhmearbA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OAi7bkPGNH5XLzGmUn6GnvRdkkkUgKsRNietrBZwvGSZZ/4=,iv:g60JaX7pABGOX/6gAn8YexqmV/m97DcMZuv4VvDE31w=,tag:0x9H4gsSpDbrfP42s2UyEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK2Z0Q3B0VUw4YWRha0Ji
            VmdOLytacXFJRWFnd2hrdjhObTJ0NUoveTFVCnovVXE4NHZ6TWtCVzVPNWNPb2lZ
            SFczY3NOVUlBMUJWTFFsbDJRTkF3azQKLS0tIC9zUUplaUp4eThQL0ltUTB1NWFn
            ZitiWXl1bEpkbktJOEVVOW52K2RxK2cKd27pxcm8K6nz/qTPoS6VnUzZX62TEHyo
            bAkpUf2uo9jEHrt6jimkt2O6bzDbfz/90dyzjrN2J+VD4iH6GD6HoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T14:41:54Z"
    mac: ENC[AES256_GCM,data:ahAP3LwK2v/M0Wj1kkQ/6gE5AiMc8sFrOvfFUZLrAEztd4MGPvMEfgAYH7vohl4Nsx+VVpq/FEfOYCsNP8I6yWu4QVt6bG3VjSuQE+HbdOACUxfZJ6AIFL9rTVQbLfWh0IOAZXbGcn2jpqEHCBsIPgAs6Cbyx0lWzk4y+zsAsds=,iv:XTXvRU03kTztOqr5epXmzwnXTFCanJqzFw+B7+RgmQs=,tag:+9aA3zhVHj0YMzExsKF3Zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
