apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+rSW3qH8hVElSXPzmBN2ye809yE=,iv:8MySrM/6cXCIUM6HWHAWASIZpv85mlFgZphzDebyg8M=,tag:1ePWsdKmVt5dapWN40FTug==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JUvHSnbg0xd+2F2+WWut84hoZV7h5DiPR9EPjhd3WwmzNCs=,iv:AzMcC1QQ5JfLBjRmrim/lK5AL3vh+2NKnEnC3aDDNZ8=,tag:Yg1DDw4yGwe85xdwcJy7Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTjlBWFc1anJUbFZ3TElt
            KzRqR2pHK1loVkVsb0pHN05tKzhjQVU4WjNjCkY0VUNHT3Evc1Z0dU5jQlYyM0Zh
            dzA5SVNveEp4RGU3VDZVTHlGc1ZyUVEKLS0tIDJrRG85WHBGTW01L3BOQlBrcXJt
            YW4xQnJJcjJSWlNIcnlSdXBlT0JlbmsKLAJifca9kOaSwvJvAduact/LIk6Ub+MO
            h4yPUP1/8gZe/Kvs0lh0YMHy0X1BFRTLcNzSsWuzwWCij1mU5lo7jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T08:09:46Z"
    mac: ENC[AES256_GCM,data:3PN0QVHCV/QQiStHrD6oLkVPVX32gpQk2vCF+BmvhwvUlFa2SFcsf770o2w3D5V+onA8d3m+OmzYzlpaBuDTav3eNcI/DCrGOGdK5LxzkVM3XykznyqPwQYke6hcItqOioidHyyExZ340wVC6XkUFPhyNIAblsC7dztRoXlfdQA=,iv:4VN6w6sponLp0IohJKhOg+xkfFMwJp6nIDk8glgzgMo=,tag:FQA4f8Hcr+ScREYm9L/jQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
