apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Odgcxu5c5I/d8sUaD+OXtzexQeI=,iv:b8brQNG+YyQyD+k2+lgxDTpC2ziGT9RuSgS6urjmn3g=,tag:eCBGNrJz3QkaaRTb2lakLg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tBBhMjkl3giJSJ2jHH/YmGdhE+jyQSGvQuMlss8yoYCXasg=,iv:dDK4MI5+fLUJ4D7y7fwKB9UPE+k/+2uk+abTsPUvJz8=,tag:iebxMgJcN4gMLOSDGbpqoQ==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:A+7VcUXjfjq3HzpZUWzf/voc9KMvuNY5RPI=,iv:eoRzAHgoFGAerIz4JcvAtPfcU/uZaAd2D/y5gQoLf+8=,tag:8VzYuQltkIzA8eMhRDEf6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaExId3B4TjhtSkVlZkNq
            WlN4NWJuZ1R3Qlp3NXVUelphOWFIaS9LMEdvClUwU1g5R0QwdnIzRlFQNkEybEVJ
            L1dYOHpvOFlROHoxaW1mdDVLOGVPZncKLS0tIHpZMG42MklGTjVrVkpMaTZ1NGVS
            RWJGNFVyNTRweDVsbEJNdTltWEZ1Q3cKJiCVYDz2d9MHusBX0NEe1+sOHIAftzHd
            QkqgyPQSAFwUl0j2T7sSS7CTGys4vq9kSoljVnm+INYsIhcqsCEyMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T07:23:28Z"
    mac: ENC[AES256_GCM,data:Bm1up9ie42iaWya0VCEt6/I7YmUsRrM9x3VFu317jb91FXwPJ+Azu9dzwOifiRXafJdlZQdGNJRroeXENLCjE9U3zEPB+j/8X/yBGK1wIaVYb6svY7yq/uH4Q+qABUFYDuHsXHMmF3kZCAw1pDzNRpCoinOTF7nq7pBW9d3a0ew=,iv:/VGVsK+LFAJvjlJ4ovHU+M/c8G1zU2cWVFMTwMzIpFY=,tag:O2EyDeKBGY/dkubdiolGGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
