# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: networking
stringData:
    cred.json: ENC[AES256_GCM,data:PgAfIbDaqf0siP/nAGLKKQtzD3tnBuOIUPR38vUl5fU2/02PWHpp4/iubOKen1o0YvQfo8TX1lphzavY2nwYlMKgS6mNl59lowh0LvA5dfgLvOM7Oybg8xSWd/a/1vbExOUCwDTH4c6cKAG4Q53MOWxzWWqf0emy7y9eOF13zz1kUTkzfOmEwEpXOHwj3twfra4bEULJmHI7IpJECccMbx91tx9kre54GsfO/NGdMphHBDCOOseq0XD4a0VYo6zPIP3v4iStSmgmDp4DFpYH5t+9VnUP2zpl,iv:NajSUVHG6QNydWs/oLMESncWV9E5dUgPkGRRBpGBms0=,tag:G9N9b0cWpPrmHLv879T/Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdnBMWURzem5ZdzQwVUtW
            SXBHcStKcVViM2NHR2FWR1BjQXAwSStMRDBjCitUS0p6ek4vd0s4bEE5YmpVT3Qx
            VTR1cmQ0MktnSTV2ckxDdWhDMGl4NWcKLS0tIFIrWG14RWxkeEVGeDEzLzZFbFBy
            T2krQmd3MmVQL2k1ZlZESk5mNis4TnMKrROhLxU3TuW1XzST51N2+DKjiiTWLrYx
            dQIPOvyFAG9Q7jiTmagyn9GA0hYRwlngnDEkhQ7JwKvwXrNJPg/23Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T08:18:19Z"
    mac: ENC[AES256_GCM,data:NY/eqECjfpusxwSMcY57YVfezwzqUf/kWPu1DVe+yG8vfHc1/FP5Ki38i1hj3qGBjXA1FZCyE6HeAy4hS49PlHkGVnNmpBTNN/zCbepl2GoT9gBBWHxq9N9yH9B0zo3+MC1pLXqFoi2H1XdwpdcH9XoB6RGID2551itc7npoq1g=,iv:ndcmnfq82zK5l7G8ViqSaWoPP+t4nr6b8uIWyea83es=,tag:UH0e27vPFw4YefyhAcDCfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
