---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-endpoint.yaml
  - ingress-route.yaml
  - redirect-path.yaml
  - rfc1918.yaml
  - tls-store.yaml
  # - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/name: traefik-misc
      app.kubernetes.io/instance: traefik-misc
