---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.19@sha256:7c00c5b6d75c24f3e951298a0e1550aae1b1b29aeb354fef1255658c4221a67f

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    enableServiceLinks: false

    env:
      TZ: ${TIMEZONE}

    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-0
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "business"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: calibre-web.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - calibre-web.${SECRET_DOMAIN}
    resources:
      requests:
        cpu: 15m
        memory: 256Mi
      limits:
        memory: 512Mi
